version: '3'

volumes:
  mongodata-volume:
    driver: local

services:
  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass test

  mongodb:
    restart: always
    image: tutum/mongodb
    environment:
      - MONGODB_USER=user7
      - MONGODB_PASS=test
      - MONGODB_DATABASE=spring-boot-sample
    volumes:
      - mongodata-volume:/data/db

  web:
    restart: always
    build: .
    depends_on:
      - redis
      - mongodb
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
