version: '2'
services:
  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass test

  mongodata:
    image: reg.news.cn/library/xh-baseimage:3.4
    volumes:
      - /data/db
    command: /bin/true

  mongodb:
    restart: always
    image: tutum/mongodb
    environment:
      - MONGODB_USER=user7
      - MONGODB_PASS=test
      - MONGODB_DATABASE=spring-boot-sample
    volumes_from:
      - mongodata

  web:
    restart: always
    build: .
    links:
      - mongodb
    ports:
      - 8080:8080