# 端口配置
server.port: 8080

# log配置
logging.file: /tmp/demo-spring-boot/root.log
logging.level.*: INFO

spring:
  thymeleaf:
    cache: false


spring.data.mongodb.uri: mongodb://user7:xinhua@192.168.83.215:27017/data-center-common