# 端口配置
server.port: 8080

# log配置
logging.file: /tmp/demo-spring-boot/root.log
logging.level.*: INFO

spring:
  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: mongodb://user7:xinhua@localhost:27017/demo-spring-boot
---
# 端口配置
server.port: 8080

# log配置
logging.file: /tmp/demo-spring-boot/root.log
logging.level.*: INFO

spring:
  profiles: docker-compose
  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: mongodb://user7:xinhua@mongodb:27017/demo-spring-boot