# 端口配置
server.port: 8080

# log配置
logging.file: /tmp/spring-boot-sample/root.log
logging.level.*: DEBUG

spring:
  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: mongodb://user7:test@localhost:27017/spring-boot-sample

  session:
    store-type: redis

  redis:
    database: 0
    host: localhost
    port: 6379
    password: test
---
# 端口配置
server.port: 8080

# log配置
logging.file: /tmp/spring-boot-sample/root.log
logging.level.*: INFO

spring:
  profiles: docker-compose
  thymeleaf:
    cache: false

  data:
    mongodb:
      uri: mongodb://user7:test@mongodb:27017/spring-boot-sample

  session:
    store-type: redis

  redis:
    database: 0
    host: redis
    port: 6379
    password: test